/** @addtogroup Game
 *  @{
 */

/**
 * Structures containing the information associated with a player event. For
 * example the MOVE event is associated with a list of entity IDs, and a
 * destination.  A SomethingEvent is an event that is sent from the client
 * to the server, indicating that the client wants to execute that event. A
 * DoSomethingEvent is a “corresponding” event from the server to the
 * clients telling the client to actually do that action; these actions are
 * ActionEvents, because they are associated with a turn.
 * @class Event
 */

#ifndef __EVENT_HPP__
# define __EVENT_HPP__

#include <serialization/serializable.hpp>
#include <network/command.hpp>
#include <mpreal/mpreal.h>
#include <world/unit.hpp>

class Event: public Serializable
{
public:
  Event(const unsigned long int id);
  Event(const Command*);
  Event();
  virtual ~Event() {}
  static unsigned long int current_id;
  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int)
  {
    ar & id;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int)
  {
    ar & id;
  }

  unsigned long int get_id() const
  {
    return this->id;
  }
  bool is_valid() const
  {
    return this->valid;
  }

private:
  Event(const Event&);
  Event& operator=(const Event&);

protected:
  unsigned long int id;
  bool valid;
};

/**
 * Event used by the server to tell a client that the action (id)
 * has been validated by the client (client_id)
 */
class OkEvent: public Event
{
public:
  OkEvent(const unsigned int id,
	  const unsigned long int client_id):
    Event(id),
    client_id(client_id)
  {}
  OkEvent(const Command*);
  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & client_id;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & client_id;
  }
  unsigned long int client_id;
};

/**
 * Just an event containing a turn number, saying that
 * the action generated by this event must be scheduled for this turn.
 */
class ActionEvent: virtual public Event
{
public:
  ActionEvent(const std::string& name):
    Event(),
    name(name)
  {}
  ActionEvent(const Command*);

  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & turn;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & turn;
  }
  unsigned long int turn;
  const std::string name;
private:
  ActionEvent(const ActionEvent&);
  ActionEvent& operator=(const ActionEvent&);
};

/**
 * An event containing an unit object.
 */
class DoUnitEvent: public ActionEvent
{
public:
  DoUnitEvent(Unit* unit):
    ActionEvent("NEW_UNIT"),
    unit(unit)
  {}
  DoUnitEvent(const Command*);

  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    ar & unit;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    ar & unit;
  }
  Unit* unit;

private:
  DoUnitEvent(const DoUnitEvent&);
  DoUnitEvent& operator=(const ActionEvent&);
};

class MoveEvent: public Event
{
public:
  MoveEvent(): Event() {}
  MoveEvent(const Command*);
  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & actors_ids & x & y;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & actors_ids & x & y;
  }

  std::vector<unsigned short> actors_ids;
  uint x;
  uint y;

private:
  MoveEvent(const MoveEvent&);
  MoveEvent& operator=(const MoveEvent&);
};

class DoMoveEvent: public ActionEvent
{
public:
  DoMoveEvent(const Command*);
  DoMoveEvent(const MoveEvent& e):
    ActionEvent("PATH"),
    actors_ids(e.actors_ids),
    x(e.x),
    y(e.y)
  {}

  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    ar & actors_ids & x & y;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    ar & actors_ids & x & y;
  }

  std::vector<unsigned short> actors_ids;
  uint x;
  uint y;
};

class BuildEvent: virtual public Event
{
public:
  BuildEvent(): Event() {}
  BuildEvent(const Command*);
  BuildEvent(const BuildEvent& e):
    Event(),
    type_id(e.type_id),
    x(e.x),
    y(e.y),
    actor(e.actor)
  { }

  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & type_id & x & y & actor;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & type_id & x & y & actor;
  }

  /**
   * The type_id of the building to build.
   */
  unsigned short type_id;
  /**
   * The top left cell on which the building is to be placed.
   */
  short x;
  short y;
  /**
   * The id of the unit thas has to build the unit.
   */
  unsigned short actor;

private:
  BuildEvent& operator=(const BuildEvent&);
};

class DoBuildEvent: public ActionEvent, public BuildEvent
{
public:
  DoBuildEvent(const Command*);
  DoBuildEvent(const BuildEvent& o):
    ActionEvent("BUILD"),
    BuildEvent(o)
  {
  }

    ~DoBuildEvent() {};

  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    BuildEvent::serialize(ar, v);
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    BuildEvent::serialize(ar, v);
  }

private:
  DoBuildEvent(const DoBuildEvent&);
  DoBuildEvent& operator=(const DoBuildEvent&);
};

class SpawnEvent: virtual public Event
{
public:
  SpawnEvent(): Event() {}
  SpawnEvent(const Command*);
  SpawnEvent(const SpawnEvent& e):
    Event(),
    type_id(e.type_id),
    actor(e.actor)
  { }

  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & type_id & actor;
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    Event::serialize(ar, v);
    ar & type_id & actor;
  }
  /**
   * The type_id of the unit to spawn.
   */
  unsigned short type_id;
  /**
   * The id of the building thas has to spawn the unit.
   */
  unsigned short actor;

private:
  SpawnEvent& operator=(const SpawnEvent&);
};

class DoSpawnEvent: public ActionEvent, public SpawnEvent
{
public:
  DoSpawnEvent(const Command*);
  DoSpawnEvent(const SpawnEvent& o):
    ActionEvent("SPAWN"),
    SpawnEvent(o)
  {
  }
  ~DoSpawnEvent() {};

  virtual void serialize(boost::archive::text_oarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    SpawnEvent::serialize(ar, v);
  }
  virtual void serialize(boost::archive::text_iarchive& ar, const unsigned int v)
  {
    ActionEvent::serialize(ar, v);
    SpawnEvent::serialize(ar, v);
  }
private:
  DoSpawnEvent(const DoSpawnEvent&);
  DoSpawnEvent& operator=(const DoSpawnEvent&);
};

#endif // __EVENT_HPP__
/**@}*/
