stages:
- build

before_script:
  - g++ --version
  - clang++ --version
  - uname -a

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
    - make -j$(nproc)
