language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsfml-dev libprotobuf-dev libboost-all

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
