/**
 * A path that a unit can follow.
 * It is generated by the server, and given to one unit, and
 * that unit moves along this path at each tick()
 */

#ifndef __PATH_HPP__
# define __PATH_HPP__

#include <mpreal/mpreal.h>

using namespace mpfr;

class Path
{
public:
  Path(const mpreal x, const mpreal y);
  Path& operator=(const Path&);
  Path(const Path&);
  ~Path();
  /**
   * Currently, a path is just a destination, but this will be changed.
   */
  mpreal x;
  mpreal y;
};


#endif // __PATH_HPP__
