/**
 * A path that a unit can follow.
 * It is generated by the server, and given to one unit, and
 * that unit moves along this path at each tick()
 */

#ifndef __PATH_HPP__
# define __PATH_HPP__

#include <world/position.hpp>
#include <list>

using Path = std::list<Position>;

#endif // __PATH_HPP__
